
CREATE TABLE user (
  id INT(8) NOT NULL AUTO_INCREMENT,
  email VARCHAR(128) NOT NULL DEFAULT '' COMMENT '用户邮箱',
  nickname VARCHAR(32) NOT NULL DEFAULT '' COMMENT '昵称',
  password VARCHAR(128) NOT NULL DEFAULT '' COMMENT '密码'
);
